stages:
    - test
    - build

variables:
    RULES_CHANGES_PATH: "**/*"
    FRONTEND_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME-frontend:latest
    BACKEND_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME-backend:latest

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    before_script:
        - mkdir -p .go
    cache:
        paths:
            - .go/pkg/mod/

backend-test:
    image: golang:1.17-buster
    stage: test
    extends: .go-cache
    script:
        - cd backend
        - go mod download
        - go mod verify
        - go test -v ./...

frontend-test:
    image: node:14-alpine
    stage: test
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - .yarn-cache/
    script:
        - cd frontend
        - yarn install --cache-folder .yarn-cache
        - yarn test:unit

backend-build:
    image: docker:latest
    stage: build
    needs: ["backend-test"]
    services:
        - docker:dind
    script:
        - docker build --tag $BACKEND_LATEST --target prod ./backend

backend-frontend:
    image: docker:latest
    stage: build
    needs: ["frontend-test"]
    services:
        - docker:dind
    script:
        - docker build --tag $FRONTEND_LATEST --target prod ./frontend
