version: "3.4"

services:
  backend:
    image: monorepo/backend
    environment:
      - LISTEN_ADDR=127.0.0.1:8080
      
  frontend:
    image: monorepo/frontend
    ports:
      - "5050:5050"

    environment:
      - BACKEND_URL=http://backend
      - NGINX_PORT=5050
