version: "3.4"

services:
  backend:
    build:
      context: backend
      target: dev

    ports:
      - "8081:8081"

    environment:
      - LISTEN_ADDR=0.0.0.0:8081

    command: go run .

  frontend:
    build:
      context: frontend
      target: dev

    ports:
      - "3000:3000"

    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - PROXY_URL=http://backend:8081

    command: yarn dev
